"""Observable AI-assistance signals and cross-agent handoff events. Signals are observations only."""

from __future__ import annotations

import re
from pathlib import Path, PurePosixPath
from typing import Any

from argus.collectors.classify import classify_path
from argus.collectors.commits import Commit
from argus.collectors.gitutil import read_text
from argus.evidence import EvidenceStore

_AI_FILES = re.compile(
    r"(^|/)(CLAUDE\.md|AGENTS\.md|GEMINI\.md|\.cursorrules|\.windsurfrules|\.aider[^/]*|copilot-instructions\.md)$|(^|/)(\.claude|\.cursor|\.codex|\.windsurf)/",
)
_AI_MESSAGE = re.compile(r"generated with \[?claude code|🤖|co-authored-by: (claude|copilot|cursor)|\baider:|generated by (chatgpt|copilot|claude|cursor)", re.I)
_PLACEHOLDER = re.compile(r"(?i)todo:? implement|your code here|placeholder implementation|not implemented yet|lorem ipsum|raise NotImplementedError|// \.\.\. rest of|# \.\.\. rest of|implementation goes here")


def ai_signals(repo: Path, tracked: list[str], commits: list[Commit], contributors: dict[str, Any], scc: dict[str, Any], commit_metrics: dict[str, Any], store: EvidenceStore) -> dict[str, Any]:
    src = "ai_signals"
    ai_identities = [
        {"name": c["name"], "authored_commits": c["authored_commits"], "coauthored_commits": c["coauthored_commits"]}
        for c in contributors["contributors"] if c["kind"] == "ai_tool"
    ]
    non_merge = [c for c in commits if not c.is_merge]
    ai_attributed = sum(i["authored_commits"] + i["coauthored_commits"] for i in ai_identities)
    ai_messages = [c for c in commits if _AI_MESSAGE.search(c.subject + "\n" + c.body)]
    config_files = [f for f in tracked if _AI_FILES.search(f)]
    placeholders = []
    for f in tracked:
        if classify_path(f) != "source":
            continue
        text = read_text(repo, f, limit=400_000)
        if not text:
            continue
        n = len(_PLACEHOLDER.findall(text))
        if n:
            placeholders.append({"file": f, "placeholder_markers": n})
    placeholders.sort(key=lambda p: -p["placeholder_markers"])
    data = {
        "ai_tool_identities_in_history": ai_identities,
        "commits_attributed_to_ai_tools": ai_attributed,
        "share_of_non_merge_commits_with_ai_attribution": round(ai_attributed / max(1, len(non_merge)), 4),
        "commits_with_ai_tool_markers_in_message": len(ai_messages),
        "ai_assistant_config_files": config_files[:20],
        "comment_ratio": scc.get("comment_ratio"),
        "large_commits": commit_metrics["granularity"]["large_commits"],
        "largest_commit_share_of_meaningful_source": max((r["share_of_all_meaningful_additions"] for r in commit_metrics["granularity"]["largest_commits"]), default=0.0),
        "placeholder_markers": {"files": len(placeholders), "total": sum(p["placeholder_markers"] for p in placeholders), "examples": placeholders[:8]},
        "note": "Explicit attribution (trailers, tool config files) is direct evidence of AI tool usage. Style-based indicators are weak and cannot establish that code was AI-generated.",
    }
    ev = store.add("ai_signals", src, f"{ai_attributed} commit(s) with explicit AI-tool attribution; {len(config_files)} AI-assistant config file(s)", data)
    return {**data, "evidence": {"ai_signals": ev}}


def handoffs(tracked: list[str], readme: dict[str, Any], ci: dict[str, Any], hygiene: dict[str, Any], similarity: dict[str, Any]) -> list[dict[str, Any]]:
    events: list[dict[str, Any]] = []
    models = [f for f in tracked if classify_path(f) == "model_artifact"]
    datasets = [f for f in tracked if classify_path(f) == "dataset"]
    training = [f for f in tracked if re.search(r"(train|fit|evaluate|eval|metrics)[^/]*\.(py|ipynb)$", PurePosixPath(f).name, re.I)]
    if readme.get("ml_claims") or models:
        events.append(
            {
                "event": "ML_CLAIM_REQUIRES_VALIDATION", "to": "ML Evaluator",
                "claims": readme.get("ml_claims", []), "model_files": models[:20], "training_or_evaluation_scripts": training[:20],
                "datasets": datasets[:20],
                "note": "ARGUS does not judge model quality, overfitting or leakage.",
            }
        )
    events.append(
        {
            "event": "REQUIREMENT_EVIDENCE", "to": "Requirements Fulfillment Agent", "requirement": "CI/CD pipeline",
            "evidence": ci["workflow_files"] + ci["other_ci_files"],
            "status": "NOT_PRESENT" if not (ci["workflow_files"] or ci["other_ci_files"]) else ("PARTIAL" if ci["consistency_findings"] else "PRESENT"),
        }
    )
    events.append(
        {
            "event": "REQUIREMENT_EVIDENCE", "to": "Requirements Fulfillment Agent", "requirement": "Automated tests",
            "evidence": [f for f in tracked if classify_path(f) == "tests"][:20],
            "status": "PRESENT" if hygiene["structure"]["has_tests"] else "NOT_PRESENT",
            "note": "Presence only; ARGUS does not execute tests.",
        }
    )
    if readme.get("claims"):
        events.append(
            {
                "event": "REQUIREMENT_EVIDENCE", "to": "Requirements Fulfillment Agent", "requirement": "README technology claims",
                "evidence": [{"technology": c["technology"], "status": c["status"]} for c in readme["claims"]],
                "status": "PARTIAL" if any(c["status"] != "VERIFIED" for c in readme["claims"]) else "PRESENT",
            }
        )
    exceeded = [c for c in similarity.get("comparisons", []) if c.get("threshold_exceeded")]
    if exceeded:
        events.append(
            {
                "event": "QA_REVIEW_REQUESTED", "to": "QA / Similarity Evaluator",
                "reason": "Meaningful-source similarity at or above the configured threshold",
                "comparisons": [{"source": c["comparison_source"], "similarity_estimate": c["similarity_estimate"]} for c in exceeded],
            }
        )
    return events
